Algoritmo "Aprovado ou reprovado"
"média sete"
Var
      n,m:inteiro
      media:real
      p:caractere
Inicio
      Escreval("              - Escola da Mousse -  ")
      Escreva("Primeira Nota:")
      Leia(n)
      Escreva("Segunda Nota:")
      Leia(m)
      Se ((m+n)/2>=7)entao
         Escreva("APROVADO")
      senao
           Escreva("REPROVADO")
      fimse
      
fimalgoritmo